### ISSUE TITLE
Establishing Focusable Element Criteria

### ISSUE THREAD

**Issue by rustle** [Choominator/Vosh#1]
I'd like to kick off a discussion of what criteria might be used to decide if an element should be focusable.

I'm going to assume the goal is a flattened hierarchy similar to NVDA or VoiceOver in QuickNav.

Here are some initial criteria I've come up with:

1. Role/subrole: Many role/subrole combinations will always need to be focusable like button and textfield and therefore can largely short-circuit any further considerations of eligibility for focus. There may be caveats such as malformed elements. For example a button that lacks any actions.
2. Presence of a label/title/titleuielement/value: Combined with role/subrole the presence of a label/title/value probably shouldn't be determinative but should make an element a likely candidate for focus.
3. Hierarchy: 
    * Some elements make sense to focus as summary elements. A group with three read only text elements inside it is potentially more legible merged into a single text element that replaces the group.
    * Some roles like table/outline/list demarcate containers so it may be useful to allow focus to land on them as landmarks even if they lack their own label.
    * Child elements of a container, like a table, will need to be focusable for the semantics of the table to be legible. The criteria may be as simple as immediate children of semantic containers or heuristic if we want to dive deeper into descendants.

Roles that should always allow focus (not comprehensive):

- Table
- Outline
- List
- List/CollectionList
- List/SectionList
- Button
- Switch
- TextField
- TextArea
- WebArea

I'll make edits here or add comments as things move along.

**Comment by Choominator** [comment]
Thanks for looking into this. Those are indeed good suggestions.. I'll implement them, publish the changes to a secondary branch, and report back.

**Comment by Choominator** [comment]
After nearly a week of reading element dumps and tweaking the code, I think that I found decent criteria to determine whether an accessibility element is a useful leaf or container, at least the behavior of the code in the `interesting-element-criteria` branch seems to closely match VoiceOver's. Regular applications continue to have a slightly flattened navigation hierarchy since I noticed that they are way too complex for totally flat navigation, but web areas are completely flat.

The next step to resolve this issue is to work on the spoken announcements, as despite some tweaks, Vosh isn't yet reading content as well as VoiceOver.
